/**:
  ros__parameters:
    camera_names: ["camera_1","camera_2","camera_3"]
    camera_1:
      frame_id: "camera_top/camera_link"
      pixel_format: bgr8
      serial_no: 210900907
      fps: 20
      width: 720
      height: 465
      flip_enable: false
      camera_info_url: "file:///home/volt/projects/volt_drivers_ws/src/arena_camera/config/camera_front_quarter.yaml"
    camera_2:
      frame_id: "camera_left/camera_link"
      pixel_format: bgr8
      serial_no: 210900909
      fps: 15
      width: 720
      height: 465
      flip_enable: false
      camera_info_url: "file:///home/volt/projects/volt_drivers_ws/src/arena_camera/config/camera_left_quarter.yaml"
    camera_3:
      frame_id: "camera_right/camera_link"
      pixel_format: bgr8
      serial_no: 210900319
      fps: 15
      width: 720
      height: 465
      flip_enable: false
      camera_info_url: "file:///home/volt/projects/volt_drivers_ws/src/arena_camera/config/camera_right_quarter.yaml"
